use_frameworks!
platform :ios, '13.0'

target 'ChronusDS_Example' do
  pod 'ChronusDS', :path => '../'
  pod 'SnapKit', '~> 5.0.0'
  
  target 'ChronusDS_Tests' do
    inherit! :search_paths

    
  end
end
