source "https://github.com/CocoaPods/Specs.git"

use_frameworks!

platform :ios, '13.0'

target 'DSKit_Example' do
  pod 'DSKit', :path => '../'

  target 'DSKit_Tests' do
    inherit! :search_paths

    
  end
end
